<?php

namespace Acme\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AcmeStoreBundle:Product p ORDER BY p.name ASC')
            ->getResult();
    }
    public function findOneByIdJoinedToCategory($id)
    {
        $query = $this->getEntityManager()
                ->createQuery('
                    Select p , c From AcmeStoreBundle:Product p
                    Join p.cateagory c
                    Where p.id = :id
                ')->setParameter('id',$id);

        try{
            return $query->getSingleResult();
        }catch (\Doctrine\ORM\NoResultException $e){
            return null;
        }
    }
}
