acme_hello:
    resource: "@AcmeHelloBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /hello
acme_hello_category:
    resource: "@AcmeHelloBundle/Controller/CategoryController.php"
    type:     annotation    