acme_hello_homepage:
    path:     /hello/{name}/{nickname}
    defaults: { _controller: AcmeHelloBundle:Default:index,_format: html }
    # _formant : html , json , ....
acme_hello_redirecting:
    path:     /hello/redirecting/
    defaults: { _controller: AcmeHelloBundle:Default:redirecting}
acme_hello_forwarding:
    path:     /hello/forwarding/
    defaults: { _controller: AcmeHelloBundle:Default:forwarding}
_helloabc:
    resource: "@AcmeHelloBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /helloabc