parameters:
#    acme_hello.example.class: Acme\HelloBundle\Example

services:
#    acme_hello.example:
#        class: %acme_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#    acme_hello.routing_loader:
#        class: Acme\HelloBundle\Routing\ExtraLoader
#        tags:
#            - { name: routing.loader }