Acme\HelloBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: Acme\HelloBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
