Acme\HelloBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Acme\HelloBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        'firstname':
            type: string
            length: 255
            column: 'firstname'
        'lastname':
            type: string
            length: 255
            column: 'lastname'
        'username':
            type: string
            length: 255
            column: 'username'
        'password':
            type: string
            length: 255
            column: 'password'
    lifecycleCallbacks: {  }
